### ISSUE TITLE
Wordpress 4.0 ?

### ISSUE THREAD

**Issue by crisc2000** [tronsha/wp-lightbox-plugin#8]
you have written in the plugin specs https://plugins.svn.wordpress.org/mpcx-lightbox/tags/1.1.5/readme.txt that this require Wordpress 4.0 . 
Are you sure this plugin require at least WP 4.0 ?
In your recent versions you are using "add_inline_style" that according to docs require Wp 3.3 
https://codex.wordpress.org/Function_Reference/wp_add_inline_style#Change_Log

**Comment by tronsha** [comment]
you are of course right, but I just tested the plugin since version 4.0.

**Comment by crisc2000** [comment]
one question. 
you have build this file https://github.com/tronsha/wp-lightbox-plugin/blob/master/wp-functions.md  manually by browsing the codex or there is a software that scan the plugin and build this automatically?

**Comment by tronsha** [comment]
I created it manually. But a tool for this would be nice.

**Comment by crisc2000** [comment]
I planed to build a tool that scan files in a directory searching wordpress functions (based on this https://github.com/hasinhayder/wp-functions-list ) and generate a report.

But it seems someone already invented the wheel before me 
https://wpseek.com/pluginfilecheck/
